apiVersion: v1
kind: Service
metadata:
  name: cicd-python-app-service
spec:
  selector:
    app: cicd-python-app
  type: LoadBalancer  # use NodePort if using minikube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
